### ISSUE TITLE
[feature]Follow the `default-run` field in 'Cargo.toml' just like `cargo run`

### ISSUE THREAD

**Issue by viruscamp** [dtolnay/cargo-expand#184]
Would you please add the feature:   
Follow the `default-run` field in 'Cargo.toml' just like `cargo run`
See https://doc.rust-lang.org/cargo/reference/manifest.html#the-default-run-field

`cargo expand` will just work as `cargo expand --bin a`, with the following configuration:
```toml
[package]
default-run = "a"

[[bin]]
name = "a"
path = "a.rs"

[[bin]]
name = "b"
path = "b.rs"
```
