### ISSUE TITLE
Tempdir is only needed on unix

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/cargo-expand#21]
The dependency should be:

```toml
[target."cfg(unix)".dependencies]
tempdir = "0.3"
```
