### ISSUE TITLE
adjust the default color disposition in .cargo/config

### ISSUE THREAD

**Issue by ahl** [dtolnay/cargo-expand#76]
It would be great if I could set `--color always` to be the default. Maybe like this:

```toml
[expand]
theme = "TwoDark"
color = "always"
```

If that sounds reasonable I'd be happy to submit a PR--and thanks for building this!
